---
storage:
  driver:
    control:
      timeoutMillis: int
    event:
      batch: boolean
      key:
        enabled: boolean
        count: long
      timeoutMillis: int
    scaling:
      type: string
      rate: int
      factor: int
      segments: int
    stream:
      data: string
  namespace: string
  net:
    bindBacklogSize: int
    interestOpQueued: boolean
    keepAlive: boolean
    linger: int
    reuseAddr: boolean
    rcvBuf: int
    sndBuf: int
    tcpNoDelay: boolean
    timeoutMillis: int
    ssl: boolean
    uri:
      schema: string
    node:
      addrs: list
      port: int
      connAttemptsLimit: int
